### PR TITLE
Use latest lpython release

### PR DESCRIPTION
**Pull request by ubaidsk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ubaidsk** [comment]
@conda-forge-admin, please rerender

**Review by certik — APPROVED** [review]
I think it looks great, thanks!

**Review by certik — APPROVED** [review]

**Comment by ubaidsk** [comment]
@certik do we need to rerender again (as we added a new commit after the previous rerender)?

**Comment by certik** [comment]
You can. I think it will do nothing.

**Comment by ubaidsk** [comment]
@conda-forge-admin, please rerender

**Comment by ubaidsk** [comment]
>I tried to rerender for you, but it looks like there was nothing to do.

Great! It looks like we just need to re-render once.

**Pull request merged**
